# Generated by Django 3.0.7 on 2020-06-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=25)),
                ('name2', models.CharField(max_length=25)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
